
services:
  bind9:
    build: .
    container_name: bind9-container
    environment:
      - TZ=UTC
    ports:
      - "30053:53"
      - "30053:53/udp"
      - "3000:3000"
    restart: always
    volumes:
      - ./docker_config/bind:/etc/bind
      - .:/app
    networks:
      - bind9-network

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql-container
    env_file:
      - .env
    volumes:
      - ./docker_config/mysql-data:/var/lib/mysql
    depends_on:
      - bind9
      
    restart: always
    networks:
      - bind9-network

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    env_file:
      - .env
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_USER=${MYSQL_USER} # Same user as in the MySQL setup
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3001:80" # Access phpMyAdmin on http://localhost:3000
    depends_on:
      - mysql
    restart: always
    networks:
      - bind9-network

# Docker Networks
networks:
  bind9-network:
    driver: bridge